[build]
<<<<<<< HEAD
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"
=======
  command = "hugo --gc --minify -b $URL"
>>>>>>> 21e9d32 (New Website Change)
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"
<<<<<<< HEAD
  NODE_VERSION = "21.1.0"
=======
>>>>>>> 21e9d32 (New Website Change)

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
<<<<<<< HEAD
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"
=======
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
>>>>>>> 21e9d32 (New Website Change)

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
